### ISSUE TITLE
Training settings for MiB+UCD and PLOP+UCD

### ISSUE THREAD

**Issue by dipamgoswami** [ygjwd12345/UCD#1]
Hello, 

Thanks for sharing the code. 

I am looking to reproduce the results using MiB+UCD and PLOP+UCD. Can you please share the training settings and scripts for that?

**Comment by ygjwd12345** [comment]
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root ./dataset --batch_size 6 --dataset voc --name att --task 15-5s --step 0 --lr 0.01 --epochs 30 --method att
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root ./dataset --batch_size 6 --dataset voc --name att --task 15-5s --step 1 --lr 0.001 --epochs 30 --method att
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root ./dataset --batch_size 6 --dataset voc --name att --task 15-5s --step 2 --lr 0.001 --epochs 30 --method att
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root ./dataset --batch_size 6 --dataset voc --name att --task 15-5s --step 3 --lr 0.001 --epochs 30 --method att
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root ./dataset --batch_size 6 --dataset voc --name att --task 15-5s --step 4 --lr 0.001 --epochs 30 --method att
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node=4 run.py --data_root ./dataset --batch_size 6 --dataset voc --name att --task 15-5s --step 5 --lr 0.001 --epochs 30 --method att

**Comment by ygjwd12345** [comment]
For PLOP
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 0 --lr 0.01 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 1 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 2 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 3 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 4 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m torch.distributed.launch --master_port 29501 --nproc_per_node=4 run.py  --data_root /home/AIL-net/dataset/PascalVOC12 --overlap --batch_size 6 --dataset voc --name PLOP --task 15-5s --step 5 --lr 0.001 --epochs 30 --method PLOP --opt_level O1 --checkpoint checkpoints/step/;

**Comment by ygjwd12345** [comment]
but, in this code, we only provide mib+ucd

**Comment by dipamgoswami** [comment]
Thanks for providing the commands.

Can you clarify if the training settings in https://github.com/ygjwd12345/UCD/blob/main/argparser.py for UCD means the MiB+UCD setting?
`if opts.method == 'UCD':
            opts.loss_kd = 10
            opts.unce = True
            opts.unkd = True
            opts.init_balanced = True`

I do not see any settings for the att method.

**Comment by ygjwd12345** [comment]
yes, the setting is the same
