### ISSUE TITLE
Training issues with PixelConLossV2:

### ISSUE THREAD

**Issue by dipamgoswami** [ygjwd12345/UCD#2]
The PixelConLossV2 loss takes 5 arguments: 
https://github.com/ygjwd12345/UCD/blob/cc735467ec9112bbf89c4f82d95ab0984159f6ce/utils/loss.py#L412
but only 3 values are passed in https://github.com/ygjwd12345/UCD/blob/cc735467ec9112bbf89c4f82d95ab0984159f6ce/train.py#L116

The code is giving an error for this. 
@ygjwd12345 Can you check the code once and update it?

**Comment by ygjwd12345** [comment]
Sorry for that.  you also need to change https://github.com/ygjwd12345/UCD/blob/cc735467ec9112bbf89c4f82d95ab0984159f6ce/train.py#L115
to get five value

**Comment by ygjwd12345** [comment]
Now I have left the original lab. So it is also difficult for me to debug them.
So sorry about that.
