### ISSUE TITLE
Visual Results on VOC

### ISSUE THREAD

**Issue by XinyueZhangHust** [ygjwd12345/UCD#3]
I find both the experimental results and the innovative aspects highly fascinating. Could you kindly provide me with visual results from the testing on the VOC dataset for the following configurations: 10-1, 2-2, 19-1, 15-5, and 15-1? We would like to reference your paper in our research and discuss the relevant experiments and algorithms. Thank you sincerely for taking the time to respond.

**Comment by ygjwd12345** [comment]
Thanks for your attention. You can visualization results in [Voc 15-1](https://www.dropbox.com/scl/fi/kw2ccpc3hh1o8hjduynhh/vis.pptx?rlkey=3izgcli0yr89fauk74fabwnxd&st=9ukher98&dl=0), [Voc 15-5](https://www.dropbox.com/scl/fi/i8kmy1gak0x92wfejvwae/voc_qua.zip?rlkey=fmmbqzpnwszh01pvpjog499u7&st=dy61myz1&dl=0),[ADE 100-50](https://www.dropbox.com/scl/fi/da05aslsw2ti5qxlrypvw/ade_qua.zip?rlkey=b4y145wostltxjrth26kms354&st=905rp3yj&dl=0).
Hope they could help for your work.

**Comment by XinyueZhangHust** [comment]
Thanks for your prompt response and assistance.

**Comment by XinyueZhangHust** [comment]
usage: run.py [-h] [--local_rank LOCAL_RANK] [--random_seed RANDOM_SEED]
              [--num_workers NUM_WORKERS] [--data_root DATA_ROOT]
              [--dataset {voc,ade,city}] [--num_classes NUM_CLASSES]
              [--method {FT,LWF,LWF-MC,ILT,EWC,RW,PI,MiB,att}]
              [--epochs EPOCHS] [--fix_bn] [--batch_size BATCH_SIZE]
              [--crop_size CROP_SIZE] [--lr LR] [--momentum MOMENTUM]
              [--weight_decay WEIGHT_DECAY] [--lr_policy {poly,step}]
              [--lr_decay_step LR_DECAY_STEP]
              [--lr_decay_factor LR_DECAY_FACTOR] [--lr_power LR_POWER]
              [--bce] [--val_on_trainset] [--cross_val] [--crop_val]
              [--logdir LOGDIR] [--name NAME] [--sample_num SAMPLE_NUM]
              [--debug] [--visualize] [--print_interval PRINT_INTERVAL]
              [--val_interval VAL_INTERVAL] [--ckpt_interval CKPT_INTERVAL]
              [--backbone {resnet50,resnet101}] [--output_stride {8,16}]
              [--no_pretrained] [--norm_act {iabn_sync,iabn,abn,std}]
              [--fusion-mode NAME] [--pooling POOLING]
              [--temperature TEMPERATURE] [--test] [--ckpt CKPT] [--freeze]
              [--loss_de LOSS_DE] [--loss_kd LOSS_KD]
              [--regularizer {ewc,rw,pi}] [--reg_importance REG_IMPORTANCE]
              [--reg_alpha REG_ALPHA] [--reg_no_normalize]
              [--reg_iterations REG_ITERATIONS] [--icarl]
              [--icarl_importance ICARL_IMPORTANCE] [--icarl_disjoint]
              [--icarl_bkg] [--init_balanced] [--unkd] [--alpha ALPHA]
              [--unce]
              [--task {offline,19-1,19-1b,15-5,15-5s,10-10,10-10s,10-5-5,offline,100-50,100-50b,100-50c,100-10,100-10b,100-10c,50,50b,50c,offline,17-2,13-6,13-6s}]
              [--step STEP] [--no_mask] [--overlap] [--step_ckpt STEP_CKPT]
              [--opt_level {O0,O1,O2,O3}] [--MASTER_PORT MASTER_PORT]
run.py: error: argument --method: invalid choice: 'UCD' (choose from 'FT', 'LWF', 'LWF-MC', 'ILT', 'EWC', 'RW', 'PI', 'MiB', 'att')

**Comment by XinyueZhangHust** [comment]
Is there an issue with my operation if I cannot find the 'UCD' configuration in the '--method' option when running 'run.py'?

**Comment by ygjwd12345** [comment]
the contrastive learning method is applied in train or pre-train. On the evaluation, you should select related baseline method.

**Comment by XinyueZhangHust** [comment]
Would you be able to provide a trained .pth file, if it's convenient for you?

**Comment by ygjwd12345** [comment]
I did not take checkpoints away from my original lab. I am sorry about that.

**Comment by XinyueZhangHust** [comment]
Thank you for your response. 

I have trained using the following command:
 python3 -m torch.distributed.launch run.py --data_root VOCdevkit --overlap --batch_size 6 --dataset voc --name MiB --task 19-1 --step 0 --lr 0.01 --epochs 30 --method MiB --opt_level O1. 

After training, I will perform testing using the following command: 
python3 -m torch.distributed.launch run.py --data_root VOCdevkit --overlap --batch_size 6 --dataset voc --name MiB --task 19-1 --step 1 --lr 0.01 --epochs 30 --method MiB --opt_level O1 --test.

 Is there anything wrong with this operation?

**Comment by ygjwd12345** [comment]
The train steps should have multiple steps such as task 19-1 step 0   19-1 step 1. As for evaluation, I am not 100% sure about it. I highly recommend running [MiB](https://github.com/fcdl94/MiB/tree/master) before you run following works.

**Comment by XinyueZhangHust** [comment]
Thank you for your response. I will proceed with the instructions you provided.

**Comment by ygjwd12345** [comment]
The last tip: the continual learning's attention has moved to the transformer, prompt tuning/engineering, and LLM/LVM. If I were you, I would figure out MiB and move to the new SOTA.

**Comment by XinyueZhangHust** [comment]
I comprehend and will investigate the information you provided. I genuinely appreciate your valuable suggestions. 
Thank you once again for your insights. Wishing you all the best!
